github:
  description: "An OSGi bundle that provides a SAML2 Web Profile Service Provider\
    \ Authentication for Apache Sling"
  labels:
  - "sling"
  - "java"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
